# Generated by Django 3.2.13 on 2022-06-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_project', models.CharField(max_length=32)),
                ('note', models.CharField(max_length=5000)),
                ('create_todo', models.PositiveIntegerField()),
                ('update_todo', models.PositiveIntegerField()),
                ('author', models.CharField(max_length=32, verbose_name='Имя автора')),
                ('activ_is', models.BooleanField(verbose_name='Активность заметки')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название проекта')),
                ('link', models.URLField(verbose_name='Ссылка на проект')),
                ('authors', models.ManyToManyField(to='todoapp.Todo')),
            ],
        ),
    ]
