# Generated by Django 3.2.13 on 2022-06-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='authors',
            field=models.ManyToManyField(to='todoapp.Todo', verbose_name='Активность проекта'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='create_todo',
            field=models.PositiveIntegerField(verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='new_project',
            field=models.CharField(max_length=32, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='note',
            field=models.CharField(max_length=5000, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='update_todo',
            field=models.PositiveIntegerField(verbose_name='Время последнего обновления'),
        ),
    ]
