# Generated by Django 3.2.13 on 2022-06-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20220609_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='authors',
            field=models.ManyToManyField(to='todoapp.Todo', verbose_name='Авторы заметок'),
        ),
    ]
