# Generated by Django 3.2.13 on 2022-06-09 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_project_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='update_todo',
            field=models.DateTimeField(verbose_name='Время последнего обновления'),
        ),
        migrations.CreateModel(
            name='AuthorTODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя автора')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия автора')),
                ('birthday_year', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('last_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.todo')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='authors',
            field=models.ManyToManyField(to='todoapp.AuthorTODO', verbose_name='Авторы заметок'),
        ),
    ]
