# Generated by Django 3.2.13 on 2022-06-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_remove_authortodo_last_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='update_todo',
            field=models.PositiveIntegerField(verbose_name='Время последнего обновления'),
        ),
    ]
