# Generated by Django 3.2.13 on 2022-06-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_alter_todo_update_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorTODO',
        ),
        migrations.AlterField(
            model_name='project',
            name='authors',
            field=models.ManyToManyField(to='todoapp.Todo', verbose_name='Авторы заметок'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='author',
            field=models.CharField(max_length=64, verbose_name='Автор заметки'),
        ),
    ]
