# Generated by Django 3.2.13 on 2022-06-12 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_auto_20220609_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('birthday_year', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='author',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='todoapp.author', verbose_name='Автор заметки'),
        ),
    ]
