# Generated by Django 3.2.13 on 2022-06-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_auto_20220612_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='author',
            field=models.CharField(max_length=64, verbose_name='Автор заметки'),
        ),
    ]
