# Generated by Django 3.2.13 on 2022-06-12 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_alter_todo_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='authors',
            field=models.ManyToManyField(to='todoapp.Author', verbose_name='Авторы заметок'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='author',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='todoapp.author', verbose_name='Автор заметки'),
        ),
    ]
