# Generated by Django 3.2.13 on 2022-06-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0010_auto_20220612_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_todo',
            field=models.DateTimeField(verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='update_todo',
            field=models.DateTimeField(verbose_name='Время последнего обновления'),
        ),
    ]
