# Generated by Django 3.2.13 on 2022-06-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0012_auto_20220613_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_todo',
            field=models.DateTimeField(verbose_name='Время создания'),
        ),
    ]
